"""empty message

Revision ID: 47f2a6d2e3bf
Revises: 404634ac4519
Create Date: 2023-12-01 16:33:21.450314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f2a6d2e3bf'
down_revision: Union[str, None] = '404634ac4519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'language')
    # ### end Alembic commands ###
