"""empty message

Revision ID: 6d61a83392f6
Revises: 9b3d992bfeb1
Create Date: 2023-11-07 13:17:01.423840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d61a83392f6'
down_revision: Union[str, None] = '9b3d992bfeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user', sa.String(), nullable=False))
    op.add_column('chats', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'language')
    op.drop_column('chats', 'user')
    # ### end Alembic commands ###
