"""empty message

Revision ID: c38a7aedae94
Revises: b31fc6732de8
Create Date: 2023-11-17 12:59:43.008403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38a7aedae94'
down_revision: Union[str, None] = 'b31fc6732de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('socket', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inlines')
    # ### end Alembic commands ###
