"""empty message

Revision ID: ee7daf179d55
Revises: c38a7aedae94
Create Date: 2023-11-21 15:58:11.016309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7daf179d55'
down_revision: Union[str, None] = 'c38a7aedae94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('recent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'recent')
    # ### end Alembic commands ###
